//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ps2Entities : DbContext
    {
        public ps2Entities()
            : base("name=ps2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Время_уроков> Время_уроков { get; set; }
        public virtual DbSet<Классы> Классы { get; set; }
        public virtual DbSet<Оценки> Оценки { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Предметы> Предметы { get; set; }
        public virtual DbSet<Расписание> Расписание { get; set; }
        public virtual DbSet<Родители> Родители { get; set; }
        public virtual DbSet<Ученики> Ученики { get; set; }
        public virtual DbSet<Учителя> Учителя { get; set; }
    }
}
