//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Классы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Классы()
        {
            this.Расписание = new HashSet<Расписание>();
            this.Ученики = new HashSet<Ученики>();
        }
    
        public System.Guid ID_класса { get; set; }
        public string Номер_класса { get; set; }
        public int Год_начала_обучения { get; set; }
        public int Год_окончания_обучения { get; set; }
        public string Специализация_класса { get; set; }
        public System.Guid ID_классного_руководителя { get; set; }
    
        public virtual Учителя Учителя { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание> Расписание { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ученики> Ученики { get; set; }
    }
}
