//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public int Оценка { get; set; }
        public System.DateTime Дата { get; set; }
        public System.Guid ID_ученика { get; set; }
        public System.Guid id_предмета { get; set; }
        public System.Guid ID_учителя { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Учителя Учителя { get; set; }
        public virtual Ученики Ученики { get; set; }
        public virtual Предметы Предметы { get; set; }
    }
}
