//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public string День_недели { get; set; }
        public int Номер_урока { get; set; }
        public System.Guid ID_предмета { get; set; }
        public System.Guid ID_класса { get; set; }
    
        public virtual Время_уроков Время_уроков { get; set; }
        public virtual Классы Классы { get; set; }
        public virtual Предметы Предметы { get; set; }
    }
}
