//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ученики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ученики()
        {
            this.Оценки = new HashSet<Оценки>();
        }
    
        public System.Guid ID_ученика { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<long> Номер_телефона { get; set; }
        public System.Guid ID_родителя { get; set; }
        public Nullable<System.Guid> ID_класса { get; set; }
    
        public virtual Классы Классы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual Родители Родители { get; set; }
    }
}
